version: "3.1"
services:
  mysql:
    image: "mysql/mysql-server:5.7.12"
    restart: "always"
    environment:
      MYSQL_ROOT_HOST: "${DOCK_MYSQL_HOST}"
      MYSQL_ROOT_PASSWORD: "${DOCK_MYSQL_PASS}"
      MYSQL_PASSWORD: "${DOCK_MYSQL_PASS}"
      MYSQL_USER: "${DOCK_MYSQL_USER}"
      MYSQL_DATABASE: "${DOCK_MYSQL_DB}"
    ports:
      - "${DOCK_MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "${DOCK_MYSQL_HOST}" ,"-p${DOCK_MYSQL_PASS}"]
      timeout: 20s
      retries: 10